<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <AsyncEventBridgePackageVersion Condition="'$(AsyncEventBridgePackageVersion)' == ''">0.1.0</AsyncEventBridgePackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AsyncEventBridge" Version="$(AsyncEventBridgePackageVersion)" />
  </ItemGroup>
</Project>
