using System.Text;
using static AsyncEventBridge.Generators.GeneratorTypeSystem;
using static AsyncEventBridge.Generators.GeneratorSymbolAnalysis;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace AsyncEventBridge.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class AsyncEventBridgeGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "AsyncEventBridge.GenerateAsyncEventsAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targetTypes = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            static (_, _) => true,
            static (generatorContext, _) => (INamedTypeSymbol)generatorContext.TargetSymbol);

        context.RegisterSourceOutput(targetTypes, static (productionContext, typeSymbol) =>
        {
            GenerateForType(productionContext, typeSymbol);
        });
    }

    private static void GenerateForType(SourceProductionContext context, INamedTypeSymbol typeSymbol)
    {
        if (!CanGenerateForType(typeSymbol))
        {
            return;
        }

        var typeParameters = CreateTypeParameterContext(typeSymbol);
        var supportedEvents = new List<EventGenerationModel>();

        foreach (var eventSymbol in GetEventsForGeneration(
            typeSymbol,
            static current => HasGenerateAsyncEventsAttribute(current) && CanGenerateForType(current)))
        {
            if (eventSymbol.IsStatic || !CanAccessEvent(eventSymbol, typeSymbol))
            {
                continue;
            }

            var shape = EventShapeClassifier.Classify(eventSymbol);

            if (shape.Kind is not (EventShapeKind.StandardUntyped or EventShapeKind.StandardTyped) ||
                !shape.IsPayloadAsyncCompatible)
            {
                continue;
            }

            supportedEvents.Add(EventGenerationModel.Create(
                eventSymbol,
                shape,
                typeParameters,
                GetMethodAccessibility(typeSymbol, eventSymbol),
                preserveNullableAnnotations: false));
        }

        if (supportedEvents.Count == 0)
        {
            return;
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>")
            .AppendLine("#nullable enable")
            .AppendLine("namespace AsyncEventBridge")
            .AppendLine("{")
            .AppendLine();

        var extensionAccessibility = supportedEvents.Any(item => item.Accessibility == "public")
            ? "public"
            : "internal";

        source.Append(extensionAccessibility)
            .Append(" static class ")
            .Append(GetExtensionClassName(typeSymbol))
            .AppendLine()
            .AppendLine("{");

        foreach (var item in supportedEvents)
        {
            AppendWaitMethods(source, typeSymbol, item, typeParameters);
            AppendStreamMethods(source, typeSymbol, item, typeParameters);
        }

        source.AppendLine("}")
            .AppendLine("}");

        var hintName = GetExtensionClassName(typeSymbol) + ".AsyncEvents.g.cs";
        context.AddSource(hintName, SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static void AppendWaitMethods(
        StringBuilder source,
        INamedTypeSymbol typeSymbol,
        EventGenerationModel item,
        TypeParameterContext typeParameters)
    {
        var sourceType = RenderType(typeSymbol, typeParameters);
        var eventName = EscapeIdentifier(item.EventSymbol.Name);
        var methodName = item.EventSymbol.Name + "Async";
        var eventArgsType = item.PayloadType;
        var handlerType = item.HandlerType;
        var isGenericEventHandler = item.IsStandardTyped;
        var accessibility = item.Accessibility;
        var waitTypeArgument = isGenericEventHandler ? $"<{eventArgsType}>" : string.Empty;

        AppendMethod(
            source,
            sourceType,
            eventName,
            methodName,
            eventArgsType,
            handlerType,
            waitTypeArgument,
            isGenericEventHandler,
            accessibility,
            typeParameters,
            includePredicate: false,
            includeTimeout: false);

        if (isGenericEventHandler)
        {
            AppendMethod(
                source,
                sourceType,
                eventName,
                methodName,
                eventArgsType,
                handlerType,
                waitTypeArgument,
                isGenericEventHandler,
                accessibility,
                typeParameters,
                includePredicate: true,
                includeTimeout: false);
        }

        AppendMethod(
            source,
            sourceType,
            eventName,
            methodName,
            eventArgsType,
            handlerType,
            waitTypeArgument,
            isGenericEventHandler,
            accessibility,
            typeParameters,
            includePredicate: false,
            includeTimeout: true);

        if (isGenericEventHandler)
        {
            AppendMethod(
                source,
                sourceType,
                eventName,
                methodName,
                eventArgsType,
                handlerType,
                waitTypeArgument,
                isGenericEventHandler,
                accessibility,
                typeParameters,
                includePredicate: true,
                includeTimeout: true);
        }
    }

    private static void AppendStreamMethods(
        StringBuilder source,
        INamedTypeSymbol typeSymbol,
        EventGenerationModel item,
        TypeParameterContext typeParameters)
    {
        var sourceType = RenderType(typeSymbol, typeParameters);
        var eventName = EscapeIdentifier(item.EventSymbol.Name);
        var methodName = item.EventSymbol.Name + "Stream";
        var eventArgsType = item.PayloadType;
        var handlerType = item.HandlerType;
        var isGenericEventHandler = item.IsStandardTyped;
        var accessibility = item.Accessibility;

        AppendStreamMethod(
            source,
            sourceType,
            eventName,
            methodName,
            eventArgsType,
            handlerType,
            isGenericEventHandler,
            accessibility,
            typeParameters,
            includePredicate: false,
            includeOptions: false);

        AppendStreamMethod(
            source,
            sourceType,
            eventName,
            methodName,
            eventArgsType,
            handlerType,
            isGenericEventHandler,
            accessibility,
            typeParameters,
            includePredicate: false,
            includeOptions: true);

        if (isGenericEventHandler)
        {
            AppendStreamMethod(
                source,
                sourceType,
                eventName,
                methodName,
                eventArgsType,
                handlerType,
                isGenericEventHandler,
                accessibility,
                typeParameters,
                includePredicate: true,
                includeOptions: false);

            AppendStreamMethod(
                source,
                sourceType,
                eventName,
                methodName,
                eventArgsType,
                handlerType,
                isGenericEventHandler,
                accessibility,
                typeParameters,
                includePredicate: true,
                includeOptions: true);
        }
    }

    private static void AppendMethod(
        StringBuilder source,
        string sourceType,
        string eventName,
        string methodName,
        string eventArgsType,
        string handlerType,
        string waitTypeArgument,
        bool isGenericEventHandler,
        string accessibility,
        TypeParameterContext typeParameters,
        bool includePredicate,
        bool includeTimeout)
    {
        source.Append("    ")
            .Append(accessibility)
            .Append(" static global::System.Threading.Tasks.Task");

        if (isGenericEventHandler)
        {
            source.Append('<')
                .Append(eventArgsType)
                .Append('>');
        }

        source.Append(' ')
            .Append(methodName);
        AppendMethodTypeParameters(source, typeParameters);
        source.Append("(this ")
            .Append(sourceType)
            .Append(" source, ");

        if (includePredicate)
        {
            source.Append("global::System.Predicate<")
                .Append(eventArgsType)
                .Append("> predicate, ");
        }

        if (includeTimeout)
        {
            source.Append("global::System.TimeSpan timeout, ");
        }

        source.Append("global::System.Threading.CancellationToken cancellationToken = default");

        if (includeTimeout)
        {
            source.Append(", global::System.TimeProvider? timeProvider = null");
        }

        source.Append(')');
        AppendMethodConstraints(source, typeParameters);
        source.AppendLine()
            .AppendLine("    {")
            .AppendLine("        if (source is null)")
            .AppendLine("        {")
            .AppendLine("            throw new global::System.ArgumentNullException(nameof(source));")
            .AppendLine("        }")
            .AppendLine();

        if (includePredicate)
        {
            source.AppendLine("        if (predicate is null)")
                .AppendLine("        {")
                .AppendLine("            throw new global::System.ArgumentNullException(nameof(predicate));")
                .AppendLine("        }")
                .AppendLine();
        }

        source.Append("        return global::AsyncEventBridge.EventAwaiter.WaitAsync")
            .Append(waitTypeArgument)
            .AppendLine("(")
            .Append("            (")
            .Append(handlerType)
            .Append(" handler) => source.")
            .Append(eventName)
            .AppendLine(" += handler,")
            .Append("            (")
            .Append(handlerType)
            .Append(" handler) => source.")
            .Append(eventName)
            .AppendLine(" -= handler,")
            .Append("            ")
            .AppendLine(includePredicate ? "predicate," : "null,")
            .Append("            cancellationToken");

        if (includeTimeout)
        {
            source.AppendLine(",")
                .AppendLine("            timeout,")
                .AppendLine("            timeProvider);");
        }
        else
        {
            source.AppendLine(");");
        }

        source.AppendLine("    }")
            .AppendLine();
    }

    private static void AppendStreamMethod(
        StringBuilder source,
        string sourceType,
        string eventName,
        string methodName,
        string eventArgsType,
        string handlerType,
        bool isGenericEventHandler,
        string accessibility,
        TypeParameterContext typeParameters,
        bool includePredicate,
        bool includeOptions)
    {
        source.Append("    ")
            .Append(accessibility)
            .Append(" static global::System.Collections.Generic.IAsyncEnumerable<")
            .Append(eventArgsType)
            .Append("> ")
            .Append(methodName);
        AppendMethodTypeParameters(source, typeParameters);
        source.Append("(this ")
            .Append(sourceType)
            .Append(" source, ");

        if (includePredicate)
        {
            source.Append("global::System.Predicate<")
                .Append(eventArgsType)
                .Append("> predicate, ");
        }

        if (includeOptions)
        {
            source.Append("global::AsyncEventBridge.EventStreamOptions options, ");
        }

        source.Append("global::System.Threading.CancellationToken cancellationToken = default)");
        AppendMethodConstraints(source, typeParameters);
        source.AppendLine()
            .AppendLine("    {")
            .AppendLine("        if (source is null)")
            .AppendLine("        {")
            .AppendLine("            throw new global::System.ArgumentNullException(nameof(source));")
            .AppendLine("        }")
            .AppendLine();

        if (includePredicate)
        {
            source.AppendLine("        if (predicate is null)")
                .AppendLine("        {")
                .AppendLine("            throw new global::System.ArgumentNullException(nameof(predicate));")
                .AppendLine("        }")
                .AppendLine();
        }

        if (includeOptions)
        {
            source.AppendLine("        if (options is null)")
                .AppendLine("        {")
                .AppendLine("            throw new global::System.ArgumentNullException(nameof(options));")
                .AppendLine("        }")
                .AppendLine();
        }

        source.Append("        return global::AsyncEventBridge.EventStream.Create")
            .Append(isGenericEventHandler ? $"<{eventArgsType}>" : string.Empty)
            .AppendLine("(")
            .Append("            (")
            .Append(handlerType)
            .Append(" handler) => source.")
            .Append(eventName)
            .AppendLine(" += handler,")
            .Append("            (")
            .Append(handlerType)
            .Append(" handler) => source.")
            .Append(eventName)
            .AppendLine(" -= handler,")
            .Append("            ")
            .AppendLine(includePredicate ? "predicate," : "null,")
            .Append("            ")
            .AppendLine(includeOptions ? "options," : "null,")
            .AppendLine("            cancellationToken);")
            .AppendLine("    }")
            .AppendLine();
    }





    private static bool HasGenerateAsyncEventsAttribute(INamedTypeSymbol typeSymbol) =>
        typeSymbol.GetAttributes().Any(attribute =>
            attribute.AttributeClass?.ToDisplayString() == AttributeMetadataName);

    private static string GetExtensionClassName(INamedTypeSymbol typeSymbol)
    {
        var builder = new StringBuilder();

        if (!typeSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            AppendEncodedName(builder, typeSymbol.ContainingNamespace.ToDisplayString());
            builder.Append("_DOT_");
        }

        var typeChain = new Stack<INamedTypeSymbol>();
        INamedTypeSymbol? current = typeSymbol;

        while (current is not null)
        {
            typeChain.Push(current);
            current = current.ContainingType;
        }

        var first = true;

        foreach (var type in typeChain)
        {
            if (!first)
            {
                builder.Append("_NESTED_");
            }

            AppendEncodedName(builder, type.Name);

            if (type.Arity != 0)
            {
                builder.Append("_A")
                    .Append(type.Arity);
            }

            first = false;
        }

        builder.Append("AsyncEventExtensions");
        return builder.ToString();
    }

    private static void AppendEncodedName(StringBuilder builder, string value)
    {
        foreach (var character in value)
        {
            switch (character)
            {
                case '.':
                    builder.Append("_DOT_");
                    break;
                case '_':
                    builder.Append("__");
                    break;
                default:
                    builder.Append(character);
                    break;
            }
        }
    }

}
