using System.Text;
using static AsyncEventBridge.Generators.GeneratorTypeSystem;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace AsyncEventBridge.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class AsyncEventBridgeOccurrenceGenerator : IIncrementalGenerator
{
    private const string DirectAttributeMetadataName = "AsyncEventBridge.GenerateAsyncEventsAttribute";
    private const string TargetAttributeMetadataName = "AsyncEventBridge.GenerateAsyncEventsForAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var directlyAnnotatedTypes = context.SyntaxProvider.ForAttributeWithMetadataName(
            DirectAttributeMetadataName,
            static (_, _) => true,
            static (generatorContext, _) => (INamedTypeSymbol)generatorContext.TargetSymbol);

        context.RegisterSourceOutput(directlyAnnotatedTypes, static (productionContext, typeSymbol) =>
        {
            GenerateForType(
                productionContext,
                typeSymbol,
                isExternalTarget: false,
                stopAtTargetTypes: null,
                extensionSuffix: "OccurrenceAsyncEventExtensions");
        });

        context.RegisterSourceOutput(context.CompilationProvider, static (productionContext, compilation) =>
        {
            GenerateAssemblyTargets(productionContext, compilation);
        });
    }

    private static void GenerateAssemblyTargets(
        SourceProductionContext context,
        Compilation compilation)
    {
        var targets = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var attribute in compilation.Assembly.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() != TargetAttributeMetadataName ||
                attribute.ConstructorArguments.Length != 1 ||
                attribute.ConstructorArguments[0].Value is not INamedTypeSymbol requestedType)
            {
                continue;
            }

            var targetType = requestedType.IsUnboundGenericType
                ? requestedType.OriginalDefinition
                : requestedType;

            if (CanGenerateForType(targetType))
            {
                targets.Add(targetType);
            }
        }

        foreach (var typeSymbol in targets)
        {
            var isExternalTarget = !SymbolEqualityComparer.Default.Equals(
                typeSymbol.ContainingAssembly,
                compilation.Assembly);

            if (!isExternalTarget && HasDirectAttribute(typeSymbol))
            {
                continue;
            }

            GenerateForType(
                context,
                typeSymbol,
                isExternalTarget,
                targets,
                extensionSuffix: "TargetedOccurrenceAsyncEventExtensions");
        }
    }

    private static void GenerateForType(
        SourceProductionContext context,
        INamedTypeSymbol typeSymbol,
        bool isExternalTarget,
        HashSet<INamedTypeSymbol>? stopAtTargetTypes,
        string extensionSuffix)
    {
        if (!CanGenerateForType(typeSymbol))
        {
            return;
        }

        var typeParameters = CreateTypeParameterContext(typeSymbol);
        var events = new List<EventInfo>();

        foreach (var eventSymbol in GetEventsForGeneration(typeSymbol, stopAtTargetTypes))
        {
            if (eventSymbol.IsStatic ||
                !CanAccessEvent(eventSymbol, typeSymbol, isExternalTarget) ||
                !TryDescribeEvent(eventSymbol, typeParameters, out var eventInfo))
            {
                continue;
            }

            events.Add(eventInfo with
            {
                Accessibility = GetMethodAccessibility(typeSymbol, eventSymbol, eventInfo),
            });
        }

        if (events.Count == 0)
        {
            return;
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>")
            .AppendLine("#nullable enable")
            .AppendLine("namespace AsyncEventBridge")
            .AppendLine("{")
            .AppendLine();

        var classAccessibility = events.Any(item => item.Accessibility == "public")
            ? "public"
            : "internal";
        var extensionClassName = GetExtensionClassName(typeSymbol, extensionSuffix);

        source.Append(classAccessibility)
            .Append(" static class ")
            .Append(extensionClassName)
            .AppendLine()
            .AppendLine("{");

        foreach (var item in events)
        {
            AppendOccurrenceWait(source, typeSymbol, item, typeParameters, includeTimeout: false);
            AppendOccurrenceWait(source, typeSymbol, item, typeParameters, includeTimeout: true);
            AppendOccurrenceStream(source, typeSymbol, item, typeParameters, includeOptions: false);
            AppendOccurrenceStream(source, typeSymbol, item, typeParameters, includeOptions: true);
        }

        source.AppendLine("}")
            .AppendLine("}");

        context.AddSource(
            extensionClassName + ".g.cs",
            SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static void AppendOccurrenceWait(
        StringBuilder source,
        INamedTypeSymbol typeSymbol,
        EventInfo item,
        TypeParameterContext typeParameters,
        bool includeTimeout)
    {
        var sourceType = RenderType(typeSymbol, typeParameters);
        var eventName = EscapeIdentifier(item.EventSymbol.Name);
        var methodName = eventName.TrimStart('@') + "OccurrenceAsync";
        var occurrenceType = $"global::AsyncEventBridge.EventOccurrence<{item.SenderType}, {item.PayloadType}>";

        source.Append("    ")
            .Append(item.Accessibility)
            .Append(" static global::System.Threading.Tasks.Task<")
            .Append(occurrenceType)
            .Append("> ")
            .Append(methodName);
        AppendMethodTypeParameters(source, typeParameters);
        source.Append("(this ")
            .Append(sourceType)
            .Append(" source, ");

        if (includeTimeout)
        {
            source.Append("global::System.TimeSpan timeout, ");
        }

        source.Append("global::System.Threading.CancellationToken cancellationToken = default");

        if (includeTimeout)
        {
            source.Append(", global::System.TimeProvider? timeProvider = null");
        }

        source.Append(')');
        AppendMethodConstraints(source, typeParameters);
        source.AppendLine()
            .AppendLine("    {")
            .AppendLine("        if (source is null)")
            .AppendLine("        {")
            .AppendLine("            throw new global::System.ArgumentNullException(nameof(source));")
            .AppendLine("        }")
            .AppendLine()
            .Append("        ")
            .Append(item.HandlerType)
            .AppendLine("? adaptedHandler = null;")
            .AppendLine()
            .Append("        return global::AsyncEventBridge.EventOccurrenceAwaiter.WaitAsync<")
            .Append(item.SenderType)
            .Append(", ")
            .Append(item.PayloadType)
            .AppendLine(">(")
            .Append("            (global::System.EventHandler<")
            .Append(item.SenderType)
            .Append(", ")
            .Append(item.PayloadType)
            .AppendLine("> handler) =>")
            .AppendLine("            {")
            .Append("                adaptedHandler = new ")
            .Append(item.HandlerType)
            .AppendLine("((sender, payload) => handler(sender, payload));")
            .Append("                source.")
            .Append(eventName)
            .AppendLine(" += adaptedHandler;")
            .AppendLine("            },")
            .Append("            (global::System.EventHandler<")
            .Append(item.SenderType)
            .Append(", ")
            .Append(item.PayloadType)
            .AppendLine("> _) =>")
            .AppendLine("            {")
            .AppendLine("                if (adaptedHandler != null)")
            .AppendLine("                {")
            .Append("                    source.")
            .Append(eventName)
            .AppendLine(" -= adaptedHandler;")
            .AppendLine("                }")
            .AppendLine("            },")
            .AppendLine("            null,")
            .Append("            cancellationToken");

        if (includeTimeout)
        {
            source.AppendLine(",")
                .AppendLine("            timeout,")
                .AppendLine("            timeProvider);");
        }
        else
        {
            source.AppendLine(");");
        }

        source.AppendLine("    }")
            .AppendLine();
    }

    private static void AppendOccurrenceStream(
        StringBuilder source,
        INamedTypeSymbol typeSymbol,
        EventInfo item,
        TypeParameterContext typeParameters,
        bool includeOptions)
    {
        var sourceType = RenderType(typeSymbol, typeParameters);
        var eventName = EscapeIdentifier(item.EventSymbol.Name);
        var methodName = eventName.TrimStart('@') + "OccurrenceStream";
        var occurrenceType = $"global::AsyncEventBridge.EventOccurrence<{item.SenderType}, {item.PayloadType}>";

        source.Append("    ")
            .Append(item.Accessibility)
            .Append(" static global::System.Collections.Generic.IAsyncEnumerable<")
            .Append(occurrenceType)
            .Append("> ")
            .Append(methodName);
        AppendMethodTypeParameters(source, typeParameters);
        source.Append("(this ")
            .Append(sourceType)
            .Append(" source, ");

        if (includeOptions)
        {
            source.Append("global::AsyncEventBridge.EventStreamOptions options, ");
        }

        source.Append("global::System.Threading.CancellationToken cancellationToken = default)");
        AppendMethodConstraints(source, typeParameters);
        source.AppendLine()
            .AppendLine("    {")
            .AppendLine("        if (source is null)")
            .AppendLine("        {")
            .AppendLine("            throw new global::System.ArgumentNullException(nameof(source));")
            .AppendLine("        }")
            .AppendLine();

        if (includeOptions)
        {
            source.AppendLine("        if (options is null)")
                .AppendLine("        {")
                .AppendLine("            throw new global::System.ArgumentNullException(nameof(options));")
                .AppendLine("        }")
                .AppendLine();
        }

        source.Append("        ")
            .Append(item.HandlerType)
            .AppendLine("? adaptedHandler = null;")
            .AppendLine()
            .Append("        return global::AsyncEventBridge.EventOccurrenceStream.Create<")
            .Append(item.SenderType)
            .Append(", ")
            .Append(item.PayloadType)
            .AppendLine(">(")
            .Append("            (global::System.EventHandler<")
            .Append(item.SenderType)
            .Append(", ")
            .Append(item.PayloadType)
            .AppendLine("> handler) =>")
            .AppendLine("            {")
            .Append("                adaptedHandler = new ")
            .Append(item.HandlerType)
            .AppendLine("((sender, payload) => handler(sender, payload));")
            .Append("                source.")
            .Append(eventName)
            .AppendLine(" += adaptedHandler;")
            .AppendLine("            },")
            .Append("            (global::System.EventHandler<")
            .Append(item.SenderType)
            .Append(", ")
            .Append(item.PayloadType)
            .AppendLine("> _) =>")
            .AppendLine("            {")
            .AppendLine("                if (adaptedHandler != null)")
            .AppendLine("                {")
            .Append("                    source.")
            .Append(eventName)
            .AppendLine(" -= adaptedHandler;")
            .AppendLine("                }")
            .AppendLine("            },")
            .AppendLine("            null,")
            .Append("            ")
            .AppendLine(includeOptions ? "options," : "null,")
            .AppendLine("            cancellationToken);")
            .AppendLine("    }")
            .AppendLine();
    }

    private static bool TryDescribeEvent(
        IEventSymbol eventSymbol,
        TypeParameterContext typeParameters,
        out EventInfo eventInfo)
    {
        eventInfo = default;

        var shape = EventShapeClassifier.Classify(eventSymbol);

        if (shape.Kind == EventShapeKind.Unsupported ||
            !shape.IsSenderAsyncCompatible ||
            !shape.IsPayloadAsyncCompatible)
        {
            return false;
        }

        eventInfo = new EventInfo(
            eventSymbol,
            RenderType(shape.DelegateType!.WithNullableAnnotation(NullableAnnotation.NotAnnotated), typeParameters),
            RenderType(shape.SenderType!, typeParameters),
            RenderType(shape.PayloadType!, typeParameters),
            string.Empty);
        return true;
    }



    private static IEnumerable<IEventSymbol> GetEventsForGeneration(
        INamedTypeSymbol typeSymbol,
        HashSet<INamedTypeSymbol>? stopAtTargetTypes)
    {
        var hiddenNames = new HashSet<string>(StringComparer.Ordinal);
        INamedTypeSymbol? current = typeSymbol;
        var isTargetType = true;

        while (current is not null)
        {
            if (!isTargetType &&
                ((stopAtTargetTypes is not null && stopAtTargetTypes.Contains(current)) ||
                 HasDirectAttribute(current)))
            {
                yield break;
            }

            foreach (var eventSymbol in current.GetMembers().OfType<IEventSymbol>())
            {
                if (!hiddenNames.Contains(eventSymbol.Name))
                {
                    yield return eventSymbol;
                }
            }

            foreach (var member in current.GetMembers())
            {
                hiddenNames.Add(member.Name);
            }

            isTargetType = false;
            current = current.BaseType;
        }
    }

    private static bool CanAccessEvent(
        IEventSymbol eventSymbol,
        INamedTypeSymbol targetType,
        bool isExternalTarget)
    {
        if (eventSymbol.DeclaredAccessibility == Accessibility.Public)
        {
            return true;
        }

        if (isExternalTarget)
        {
            return false;
        }

        var sameAssembly = SymbolEqualityComparer.Default.Equals(
            eventSymbol.ContainingAssembly,
            targetType.ContainingAssembly);

        return sameAssembly &&
            eventSymbol.DeclaredAccessibility is Accessibility.Internal or Accessibility.ProtectedOrInternal;
    }

    private static string GetMethodAccessibility(
        INamedTypeSymbol typeSymbol,
        IEventSymbol eventSymbol,
        EventInfo eventInfo)
    {
        return IsPubliclyAccessible(typeSymbol) &&
               eventSymbol.DeclaredAccessibility == Accessibility.Public &&
               IsPubliclyAccessible(eventSymbol.Type) &&
               IsPubliclyAccessible(((INamedTypeSymbol)eventSymbol.Type).DelegateInvokeMethod!.Parameters[0].Type) &&
               IsPubliclyAccessible(((INamedTypeSymbol)eventSymbol.Type).DelegateInvokeMethod!.Parameters[1].Type)
            ? "public"
            : "internal";
    }

    private static bool IsPubliclyAccessible(ITypeSymbol typeSymbol)
    {
        if (typeSymbol is ITypeParameterSymbol)
        {
            return true;
        }

        if (typeSymbol is IArrayTypeSymbol arrayType)
        {
            return IsPubliclyAccessible(arrayType.ElementType);
        }

        if (typeSymbol is not INamedTypeSymbol namedType)
        {
            return true;
        }

        if (namedType.DeclaredAccessibility != Accessibility.Public)
        {
            return false;
        }

        if (namedType.ContainingType is not null && !IsPubliclyAccessible(namedType.ContainingType))
        {
            return false;
        }

        return namedType.TypeArguments.All(IsPubliclyAccessible);
    }

    private static bool CanGenerateForType(INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.TypeKind != TypeKind.Class)
        {
            return false;
        }

        INamedTypeSymbol? current = typeSymbol;
        while (current is not null)
        {
            if (current.ContainingType is not null &&
                current.DeclaredAccessibility is Accessibility.Private or Accessibility.Protected or Accessibility.ProtectedAndInternal)
            {
                return false;
            }

            current = current.ContainingType;
        }

        return true;
    }

    private static bool HasDirectAttribute(INamedTypeSymbol typeSymbol) =>
        typeSymbol.GetAttributes().Any(attribute =>
            attribute.AttributeClass?.ToDisplayString() == DirectAttributeMetadataName);

    private static string GetExtensionClassName(INamedTypeSymbol typeSymbol, string suffix)
    {
        var identity = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var builder = new StringBuilder(identity.Length + suffix.Length);

        foreach (var character in identity)
        {
            builder.Append(char.IsLetterOrDigit(character) ? character : '_');
        }

        return builder.Append(suffix).ToString();
    }

    private readonly record struct EventInfo(
        IEventSymbol EventSymbol,
        string HandlerType,
        string SenderType,
        string PayloadType,
        string Accessibility);

}
