using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace AsyncEventBridge.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class AsyncEventBridgeGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "AsyncEventBridge.GenerateAsyncEventsAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targetTypes = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            static (_, _) => true,
            static (generatorContext, _) => (INamedTypeSymbol)generatorContext.TargetSymbol);

        context.RegisterSourceOutput(targetTypes, static (productionContext, typeSymbol) =>
        {
            GenerateForType(productionContext, typeSymbol);
        });
    }

    private static void GenerateForType(SourceProductionContext context, INamedTypeSymbol typeSymbol)
    {
        if (!CanGenerateForType(typeSymbol))
        {
            return;
        }

        var typeParameters = CreateTypeParameterContext(typeSymbol);
        var supportedEvents = new List<EventGenerationInfo>();

        foreach (var eventSymbol in GetEventsForGeneration(typeSymbol))
        {
            if (eventSymbol.IsStatic || !CanAccessEvent(eventSymbol, typeSymbol))
            {
                continue;
            }

            if (!TryGetEventArgsType(
                    eventSymbol,
                    typeParameters,
                    out var eventArgsType,
                    out var isGenericEventHandler))
            {
                continue;
            }

            supportedEvents.Add(new EventGenerationInfo(
                eventSymbol,
                eventArgsType,
                isGenericEventHandler,
                GetMethodAccessibility(typeSymbol, eventSymbol)));
        }

        if (supportedEvents.Count == 0)
        {
            return;
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>")
            .AppendLine("#nullable enable")
            .AppendLine("namespace AsyncEventBridge")
            .AppendLine("{")
            .AppendLine();

        var extensionAccessibility = supportedEvents.Any(item => item.Accessibility == "public")
            ? "public"
            : "internal";

        source.Append(extensionAccessibility)
            .Append(" static class ")
            .Append(GetExtensionClassName(typeSymbol))
            .AppendLine()
            .AppendLine("{");

        foreach (var item in supportedEvents)
        {
            AppendWaitMethods(
                source,
                typeSymbol,
                item.EventSymbol,
                item.EventArgsType,
                item.IsGenericEventHandler,
                item.Accessibility,
                typeParameters);

            AppendStreamMethods(
                source,
                typeSymbol,
                item.EventSymbol,
                item.EventArgsType,
                item.IsGenericEventHandler,
                item.Accessibility,
                typeParameters);
        }

        source.AppendLine("}")
            .AppendLine("}");

        var hintName = GetExtensionClassName(typeSymbol) + ".AsyncEvents.g.cs";
        context.AddSource(hintName, SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static IEnumerable<IEventSymbol> GetEventsForGeneration(INamedTypeSymbol typeSymbol)
    {
        var hiddenNames = new HashSet<string>(StringComparer.Ordinal);
        INamedTypeSymbol? current = typeSymbol;
        var isTargetType = true;

        while (current is not null)
        {
            if (!isTargetType && HasGenerateAsyncEventsAttribute(current) && CanGenerateForType(current))
            {
                yield break;
            }

            foreach (var eventSymbol in current.GetMembers().OfType<IEventSymbol>())
            {
                if (!hiddenNames.Contains(eventSymbol.Name))
                {
                    yield return eventSymbol;
                }
            }

            foreach (var member in current.GetMembers())
            {
                hiddenNames.Add(member.Name);
            }

            isTargetType = false;
            current = current.BaseType;
        }
    }

    private static void AppendWaitMethods(
        StringBuilder source,
        INamedTypeSymbol typeSymbol,
        IEventSymbol eventSymbol,
        string eventArgsType,
        bool isGenericEventHandler,
        string accessibility,
        TypeParameterContext typeParameters)
    {
        var sourceType = RenderType(typeSymbol, typeParameters);
        var eventName = EscapeIdentifier(eventSymbol.Name);
        var methodName = eventSymbol.Name + "Async";
        var handlerType = isGenericEventHandler
            ? $"global::System.EventHandler<{eventArgsType}>"
            : "global::System.EventHandler";
        var waitTypeArgument = isGenericEventHandler ? $"<{eventArgsType}>" : string.Empty;

        AppendMethod(
            source,
            sourceType,
            eventName,
            methodName,
            eventArgsType,
            handlerType,
            waitTypeArgument,
            isGenericEventHandler,
            accessibility,
            typeParameters,
            includePredicate: false,
            includeTimeout: false);

        if (isGenericEventHandler)
        {
            AppendMethod(
                source,
                sourceType,
                eventName,
                methodName,
                eventArgsType,
                handlerType,
                waitTypeArgument,
                isGenericEventHandler,
                accessibility,
                typeParameters,
                includePredicate: true,
                includeTimeout: false);
        }

        AppendMethod(
            source,
            sourceType,
            eventName,
            methodName,
            eventArgsType,
            handlerType,
            waitTypeArgument,
            isGenericEventHandler,
            accessibility,
            typeParameters,
            includePredicate: false,
            includeTimeout: true);

        if (isGenericEventHandler)
        {
            AppendMethod(
                source,
                sourceType,
                eventName,
                methodName,
                eventArgsType,
                handlerType,
                waitTypeArgument,
                isGenericEventHandler,
                accessibility,
                typeParameters,
                includePredicate: true,
                includeTimeout: true);
        }
    }

    private static void AppendStreamMethods(
        StringBuilder source,
        INamedTypeSymbol typeSymbol,
        IEventSymbol eventSymbol,
        string eventArgsType,
        bool isGenericEventHandler,
        string accessibility,
        TypeParameterContext typeParameters)
    {
        var sourceType = RenderType(typeSymbol, typeParameters);
        var eventName = EscapeIdentifier(eventSymbol.Name);
        var methodName = eventSymbol.Name + "Stream";
        var handlerType = isGenericEventHandler
            ? $"global::System.EventHandler<{eventArgsType}>"
            : "global::System.EventHandler";

        AppendStreamMethod(
            source,
            sourceType,
            eventName,
            methodName,
            eventArgsType,
            handlerType,
            isGenericEventHandler,
            accessibility,
            typeParameters,
            includePredicate: false,
            includeOptions: false);

        AppendStreamMethod(
            source,
            sourceType,
            eventName,
            methodName,
            eventArgsType,
            handlerType,
            isGenericEventHandler,
            accessibility,
            typeParameters,
            includePredicate: false,
            includeOptions: true);

        if (isGenericEventHandler)
        {
            AppendStreamMethod(
                source,
                sourceType,
                eventName,
                methodName,
                eventArgsType,
                handlerType,
                isGenericEventHandler,
                accessibility,
                typeParameters,
                includePredicate: true,
                includeOptions: false);

            AppendStreamMethod(
                source,
                sourceType,
                eventName,
                methodName,
                eventArgsType,
                handlerType,
                isGenericEventHandler,
                accessibility,
                typeParameters,
                includePredicate: true,
                includeOptions: true);
        }
    }

    private static void AppendMethod(
        StringBuilder source,
        string sourceType,
        string eventName,
        string methodName,
        string eventArgsType,
        string handlerType,
        string waitTypeArgument,
        bool isGenericEventHandler,
        string accessibility,
        TypeParameterContext typeParameters,
        bool includePredicate,
        bool includeTimeout)
    {
        source.Append("    ")
            .Append(accessibility)
            .Append(" static global::System.Threading.Tasks.Task");

        if (isGenericEventHandler)
        {
            source.Append('<')
                .Append(eventArgsType)
                .Append('>');
        }

        source.Append(' ')
            .Append(methodName);
        AppendMethodTypeParameters(source, typeParameters);
        source.Append("(this ")
            .Append(sourceType)
            .Append(" source, ");

        if (includePredicate)
        {
            source.Append("global::System.Predicate<")
                .Append(eventArgsType)
                .Append("> predicate, ");
        }

        if (includeTimeout)
        {
            source.Append("global::System.TimeSpan timeout, ");
        }

        source.Append("global::System.Threading.CancellationToken cancellationToken = default");

        if (includeTimeout)
        {
            source.Append(", global::System.TimeProvider? timeProvider = null");
        }

        source.Append(')');
        AppendMethodConstraints(source, typeParameters);
        source.AppendLine()
            .AppendLine("    {")
            .AppendLine("        if (source is null)")
            .AppendLine("        {")
            .AppendLine("            throw new global::System.ArgumentNullException(nameof(source));")
            .AppendLine("        }")
            .AppendLine();

        if (includePredicate)
        {
            source.AppendLine("        if (predicate is null)")
                .AppendLine("        {")
                .AppendLine("            throw new global::System.ArgumentNullException(nameof(predicate));")
                .AppendLine("        }")
                .AppendLine();
        }

        source.Append("        return global::AsyncEventBridge.EventAwaiter.WaitAsync")
            .Append(waitTypeArgument)
            .AppendLine("(")
            .Append("            (")
            .Append(handlerType)
            .Append(" handler) => source.")
            .Append(eventName)
            .AppendLine(" += handler,")
            .Append("            (")
            .Append(handlerType)
            .Append(" handler) => source.")
            .Append(eventName)
            .AppendLine(" -= handler,")
            .Append("            ")
            .AppendLine(includePredicate ? "predicate," : "null,")
            .Append("            cancellationToken");

        if (includeTimeout)
        {
            source.AppendLine(",")
                .AppendLine("            timeout,")
                .AppendLine("            timeProvider);");
        }
        else
        {
            source.AppendLine(");");
        }

        source.AppendLine("    }")
            .AppendLine();
    }

    private static void AppendStreamMethod(
        StringBuilder source,
        string sourceType,
        string eventName,
        string methodName,
        string eventArgsType,
        string handlerType,
        bool isGenericEventHandler,
        string accessibility,
        TypeParameterContext typeParameters,
        bool includePredicate,
        bool includeOptions)
    {
        source.Append("    ")
            .Append(accessibility)
            .Append(" static global::System.Collections.Generic.IAsyncEnumerable<")
            .Append(eventArgsType)
            .Append("> ")
            .Append(methodName);
        AppendMethodTypeParameters(source, typeParameters);
        source.Append("(this ")
            .Append(sourceType)
            .Append(" source, ");

        if (includePredicate)
        {
            source.Append("global::System.Predicate<")
                .Append(eventArgsType)
                .Append("> predicate, ");
        }

        if (includeOptions)
        {
            source.Append("global::AsyncEventBridge.EventStreamOptions options, ");
        }

        source.Append("global::System.Threading.CancellationToken cancellationToken = default)");
        AppendMethodConstraints(source, typeParameters);
        source.AppendLine()
            .AppendLine("    {")
            .AppendLine("        if (source is null)")
            .AppendLine("        {")
            .AppendLine("            throw new global::System.ArgumentNullException(nameof(source));")
            .AppendLine("        }")
            .AppendLine();

        if (includePredicate)
        {
            source.AppendLine("        if (predicate is null)")
                .AppendLine("        {")
                .AppendLine("            throw new global::System.ArgumentNullException(nameof(predicate));")
                .AppendLine("        }")
                .AppendLine();
        }

        if (includeOptions)
        {
            source.AppendLine("        if (options is null)")
                .AppendLine("        {")
                .AppendLine("            throw new global::System.ArgumentNullException(nameof(options));")
                .AppendLine("        }")
                .AppendLine();
        }

        source.Append("        return global::AsyncEventBridge.EventStream.Create")
            .Append(isGenericEventHandler ? $"<{eventArgsType}>" : string.Empty)
            .AppendLine("(")
            .Append("            (")
            .Append(handlerType)
            .Append(" handler) => source.")
            .Append(eventName)
            .AppendLine(" += handler,")
            .Append("            (")
            .Append(handlerType)
            .Append(" handler) => source.")
            .Append(eventName)
            .AppendLine(" -= handler,")
            .Append("            ")
            .AppendLine(includePredicate ? "predicate," : "null,")
            .Append("            ")
            .AppendLine(includeOptions ? "options," : "null,")
            .AppendLine("            cancellationToken);")
            .AppendLine("    }")
            .AppendLine();
    }

    private static bool TryGetEventArgsType(
        IEventSymbol eventSymbol,
        TypeParameterContext typeParameters,
        out string eventArgsType,
        out bool isGenericEventHandler)
    {
        eventArgsType = string.Empty;
        isGenericEventHandler = false;

        if (eventSymbol.Type is not INamedTypeSymbol delegateType ||
            delegateType.Name != "EventHandler" ||
            delegateType.ContainingNamespace.ToDisplayString() != "System")
        {
            return false;
        }

        if (delegateType.TypeArguments.Length == 0)
        {
            eventArgsType = "global::System.EventArgs";
            return true;
        }

        if (delegateType.TypeArguments.Length != 1 ||
            !IsAsyncPayloadCompatible(delegateType.TypeArguments[0]))
        {
            return false;
        }

        eventArgsType = RenderType(delegateType.TypeArguments[0], typeParameters);
        isGenericEventHandler = true;
        return true;
    }

    private static bool IsAsyncPayloadCompatible(ITypeSymbol typeSymbol) =>
        !typeSymbol.IsRefLikeType &&
        (typeSymbol is not ITypeParameterSymbol typeParameter || !typeParameter.AllowsRefLikeType);

    private static bool CanAccessEvent(IEventSymbol eventSymbol, INamedTypeSymbol targetType)
    {
        if (eventSymbol.DeclaredAccessibility == Accessibility.Public)
        {
            return true;
        }

        var sameAssembly = SymbolEqualityComparer.Default.Equals(
            eventSymbol.ContainingAssembly,
            targetType.ContainingAssembly);

        return sameAssembly &&
            eventSymbol.DeclaredAccessibility is Accessibility.Internal or Accessibility.ProtectedOrInternal;
    }

    private static string GetMethodAccessibility(INamedTypeSymbol typeSymbol, IEventSymbol eventSymbol)
    {
        return IsPubliclyAccessible(typeSymbol) &&
               eventSymbol.DeclaredAccessibility == Accessibility.Public &&
               IsPubliclyAccessible(eventSymbol.Type)
            ? "public"
            : "internal";
    }

    private static bool IsPubliclyAccessible(ITypeSymbol typeSymbol)
    {
        if (typeSymbol is ITypeParameterSymbol)
        {
            return true;
        }

        if (typeSymbol is IArrayTypeSymbol arrayType)
        {
            return IsPubliclyAccessible(arrayType.ElementType);
        }

        if (typeSymbol is not INamedTypeSymbol namedType)
        {
            return true;
        }

        if (namedType.DeclaredAccessibility != Accessibility.Public)
        {
            return false;
        }

        if (namedType.ContainingType is not null && !IsPubliclyAccessible(namedType.ContainingType))
        {
            return false;
        }

        return namedType.TypeArguments.All(IsPubliclyAccessible);
    }

    private static bool CanGenerateForType(INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.TypeKind != TypeKind.Class)
        {
            return false;
        }

        INamedTypeSymbol? current = typeSymbol;

        while (current is not null)
        {
            if (current.DeclaredAccessibility is not (
                Accessibility.Public or
                Accessibility.Internal or
                Accessibility.ProtectedOrInternal))
            {
                return false;
            }

            current = current.ContainingType;
        }

        return true;
    }

    private static bool HasGenerateAsyncEventsAttribute(INamedTypeSymbol typeSymbol) =>
        typeSymbol.GetAttributes().Any(attribute =>
            attribute.AttributeClass?.ToDisplayString() == AttributeMetadataName);

    private static TypeParameterContext CreateTypeParameterContext(INamedTypeSymbol typeSymbol)
    {
        var typeChain = new Stack<INamedTypeSymbol>();
        INamedTypeSymbol? current = typeSymbol;

        while (current is not null)
        {
            typeChain.Push(current);
            current = current.ContainingType;
        }

        var parameters = new List<ITypeParameterSymbol>();
        var names = new Dictionary<ITypeParameterSymbol, string>(SymbolEqualityComparer.Default);
        var index = 0;

        foreach (var type in typeChain)
        {
            foreach (var parameter in type.TypeParameters)
            {
                parameters.Add(parameter);
                names.Add(parameter, "TSource" + index);
                index++;
            }
        }

        return new TypeParameterContext(parameters, names);
    }

    private static string RenderType(ITypeSymbol typeSymbol, TypeParameterContext typeParameters)
    {
        if (typeSymbol is ITypeParameterSymbol typeParameter &&
            typeParameters.Names.TryGetValue(typeParameter, out var parameterName))
        {
            return parameterName;
        }

        var builder = new StringBuilder();

        foreach (var part in typeSymbol.ToDisplayParts(SymbolDisplayFormat.FullyQualifiedFormat))
        {
            if (part.Symbol is ITypeParameterSymbol partTypeParameter &&
                typeParameters.Names.TryGetValue(partTypeParameter, out var replacement))
            {
                builder.Append(replacement);
            }
            else
            {
                builder.Append(part.ToString());
            }
        }

        return builder.ToString();
    }

    private static void AppendMethodTypeParameters(StringBuilder source, TypeParameterContext typeParameters)
    {
        if (typeParameters.Parameters.Count == 0)
        {
            return;
        }

        source.Append('<');

        for (var index = 0; index < typeParameters.Parameters.Count; index++)
        {
            if (index != 0)
            {
                source.Append(", ");
            }

            source.Append(typeParameters.Names[typeParameters.Parameters[index]]);
        }

        source.Append('>');
    }

    private static void AppendMethodConstraints(StringBuilder source, TypeParameterContext typeParameters)
    {
        foreach (var parameter in typeParameters.Parameters)
        {
            var constraints = GetConstraints(parameter, typeParameters);

            if (constraints.Count == 0)
            {
                continue;
            }

            source.AppendLine()
                .Append("        where ")
                .Append(typeParameters.Names[parameter])
                .Append(" : ")
                .Append(string.Join(", ", constraints));
        }
    }

    private static List<string> GetConstraints(
        ITypeParameterSymbol parameter,
        TypeParameterContext typeParameters)
    {
        var constraints = new List<string>();

        if (parameter.HasUnmanagedTypeConstraint)
        {
            constraints.Add("unmanaged");
        }
        else if (parameter.HasValueTypeConstraint)
        {
            constraints.Add("struct");
        }
        else if (parameter.HasReferenceTypeConstraint)
        {
            constraints.Add(
                parameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated
                    ? "class?"
                    : "class");
        }
        else if (parameter.HasNotNullConstraint)
        {
            constraints.Add("notnull");
        }

        foreach (var constraintType in parameter.ConstraintTypes)
        {
            constraints.Add(RenderType(constraintType, typeParameters));
        }

        if (parameter.HasConstructorConstraint &&
            !parameter.HasValueTypeConstraint &&
            !parameter.HasUnmanagedTypeConstraint)
        {
            constraints.Add("new()");
        }

        if (parameter.AllowsRefLikeType)
        {
            constraints.Add("allows ref struct");
        }

        return constraints;
    }

    private static string GetExtensionClassName(INamedTypeSymbol typeSymbol)
    {
        var builder = new StringBuilder();

        if (!typeSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            AppendEncodedName(builder, typeSymbol.ContainingNamespace.ToDisplayString());
            builder.Append("_DOT_");
        }

        var typeChain = new Stack<INamedTypeSymbol>();
        INamedTypeSymbol? current = typeSymbol;

        while (current is not null)
        {
            typeChain.Push(current);
            current = current.ContainingType;
        }

        var first = true;

        foreach (var type in typeChain)
        {
            if (!first)
            {
                builder.Append("_NESTED_");
            }

            AppendEncodedName(builder, type.Name);

            if (type.Arity != 0)
            {
                builder.Append("_A")
                    .Append(type.Arity);
            }

            first = false;
        }

        builder.Append("AsyncEventExtensions");
        return builder.ToString();
    }

    private static void AppendEncodedName(StringBuilder builder, string value)
    {
        foreach (var character in value)
        {
            switch (character)
            {
                case '.':
                    builder.Append("_DOT_");
                    break;
                case '_':
                    builder.Append("__");
                    break;
                default:
                    builder.Append(character);
                    break;
            }
        }
    }

    private static string EscapeIdentifier(string identifier) =>
        SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None ? identifier : "@" + identifier;

    private sealed class TypeParameterContext
    {
        internal TypeParameterContext(
            IReadOnlyList<ITypeParameterSymbol> parameters,
            IReadOnlyDictionary<ITypeParameterSymbol, string> names)
        {
            Parameters = parameters;
            Names = names;
        }

        internal IReadOnlyList<ITypeParameterSymbol> Parameters { get; }

        internal IReadOnlyDictionary<ITypeParameterSymbol, string> Names { get; }
    }

    private sealed class EventGenerationInfo
    {
        internal EventGenerationInfo(
            IEventSymbol eventSymbol,
            string eventArgsType,
            bool isGenericEventHandler,
            string accessibility)
        {
            EventSymbol = eventSymbol;
            EventArgsType = eventArgsType;
            IsGenericEventHandler = isGenericEventHandler;
            Accessibility = accessibility;
        }

        internal IEventSymbol EventSymbol { get; }

        internal string EventArgsType { get; }

        internal bool IsGenericEventHandler { get; }

        internal string Accessibility { get; }
    }
}
