using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AsyncEventBridge.Unity.Generators;

[Generator]
public sealed class AsyncEventBridgeInspectorGenerator : ISourceGenerator
{
    private const string AttributeMetadataName = "AsyncEventBridge.Unity.GenerateInspectorEventsAttribute";
    private const string MonoBehaviourMetadataName = "UnityEngine.MonoBehaviour";

    private static readonly DiagnosticDescriptor InvalidInspectorTarget = new DiagnosticDescriptor(
        id: "AEB004",
        title: "Invalid Inspector event generation target",
        messageFormat: "Type '{0}' cannot expose AsyncEventBridge Inspector events. The target must be a top-level, non-generic, partial MonoBehaviour class.",
        category: "AsyncEventBridge",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        helpLinkUri: "https://github.com/Perry3Dnl/AsyncEventBridge/blob/main/docs/diagnostics.md#aeb004");

    private static readonly DiagnosticDescriptor UnsupportedInspectorEvent = new DiagnosticDescriptor(
        id: "AEB005",
        title: "Unsupported Inspector event delegate",
        messageFormat: "Event '{0}.{1}' cannot be exposed in the Unity Inspector because delegate type '{2}' is not an EventHandler-compatible two-parameter void delegate.",
        category: "AsyncEventBridge",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        helpLinkUri: "https://github.com/Perry3Dnl/AsyncEventBridge/blob/main/docs/diagnostics.md#aeb005");

    private static readonly DiagnosticDescriptor ReservedInspectorMember = new DiagnosticDescriptor(
        id: "AEB006",
        title: "Reserved Inspector event member collision",
        messageFormat: "Type '{0}' already declares a member named 'AsyncEventBridgeEvents', which is reserved by GenerateInspectorEvents.",
        category: "AsyncEventBridge",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        helpLinkUri: "https://github.com/Perry3Dnl/AsyncEventBridge/blob/main/docs/diagnostics.md#aeb006");

    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        foreach (var typeSymbol in GetAllTypes(context.Compilation.Assembly.GlobalNamespace))
        {
            if (!HasAttribute(typeSymbol))
            {
                continue;
            }

            var location = typeSymbol.Locations.FirstOrDefault(item => item.IsInSource) ?? Location.None;
            if (!CanGenerateFor(typeSymbol))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidInspectorTarget,
                    location,
                    typeSymbol.ToDisplayString()));
                continue;
            }

            if (typeSymbol.GetMembers("AsyncEventBridgeEvents").Length != 0)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    ReservedInspectorMember,
                    location,
                    typeSymbol.ToDisplayString()));
                continue;
            }

            var supportedEvents = new List<EventInfo>();
            foreach (var eventSymbol in GetEvents(typeSymbol))
            {
                if (eventSymbol.IsStatic || !CanAccessEvent(eventSymbol, typeSymbol))
                {
                    continue;
                }

                var classification = Classify(eventSymbol);
                if (!classification.IsSupported)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        UnsupportedInspectorEvent,
                        eventSymbol.Locations.FirstOrDefault(item => item.IsInSource) ?? location,
                        typeSymbol.ToDisplayString(),
                        eventSymbol.Name,
                        eventSymbol.Type.ToDisplayString()));
                    continue;
                }

                supportedEvents.Add(new EventInfo(eventSymbol, classification));
            }

            if (supportedEvents.Count == 0)
            {
                continue;
            }

            Generate(context, typeSymbol, supportedEvents);
        }
    }

    private static void Generate(
        GeneratorExecutionContext context,
        INamedTypeSymbol typeSymbol,
        IReadOnlyList<EventInfo> events)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>")
            .AppendLine("#nullable enable");

        if (!typeSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            source.Append("namespace ")
                .Append(typeSymbol.ContainingNamespace.ToDisplayString())
                .AppendLine()
                .AppendLine("{");
        }

        source.AppendLine("[global::UnityEngine.RequireComponent(typeof(global::AsyncEventBridge.Unity.AsyncEventBridgeInspectorHost))]")
            .Append(GetAccessibility(typeSymbol))
            .Append(" partial class ")
            .Append(EscapeIdentifier(typeSymbol.Name))
            .AppendLine(" : global::AsyncEventBridge.Unity.IAsyncEventBridgeInspectorSource")
            .AppendLine("{")
            .AppendLine("    [global::System.Serializable]")
            .AppendLine("    private sealed class __AebInspectorEvents")
            .AppendLine("    {");

        foreach (var item in events)
        {
            source.Append("        public ")
                .Append(item.Classification.IsTyped
                    ? "global::UnityEngine.Events.UnityEvent<" + item.Classification.EventArgsType + ">"
                    : "global::UnityEngine.Events.UnityEvent")
                .Append(' ')
                .Append(EscapeIdentifier(item.EventSymbol.Name))
                .Append(" = new ")
                .Append(item.Classification.IsTyped
                    ? "global::UnityEngine.Events.UnityEvent<" + item.Classification.EventArgsType + ">"
                    : "global::UnityEngine.Events.UnityEvent")
                .AppendLine("();");
        }

        source.AppendLine("    }")
            .AppendLine()
            .AppendLine("    [global::UnityEngine.SerializeField]")
            .AppendLine("    private __AebInspectorEvents AsyncEventBridgeEvents = new __AebInspectorEvents();")
            .AppendLine()
            .AppendLine("    private bool __aebInspectorEventsConnected;")
            .AppendLine()
            .AppendLine("    void global::AsyncEventBridge.Unity.IAsyncEventBridgeInspectorSource.ConnectInspectorEvents()")
            .AppendLine("    {")
            .AppendLine("        if (__aebInspectorEventsConnected)")
            .AppendLine("        {")
            .AppendLine("            return;")
            .AppendLine("        }")
            .AppendLine()
            .AppendLine("        if (AsyncEventBridgeEvents is null)")
            .AppendLine("        {")
            .AppendLine("            AsyncEventBridgeEvents = new __AebInspectorEvents();")
            .AppendLine("        }")
            .AppendLine()
            .AppendLine("        __aebInspectorEventsConnected = true;")
            .AppendLine("        try")
            .AppendLine("        {");

        foreach (var item in events)
        {
            source.Append("            this.")
                .Append(EscapeIdentifier(item.EventSymbol.Name))
                .Append(" += ")
                .Append(GetHandlerName(item.EventSymbol.Name))
                .AppendLine(";");
        }

        source.AppendLine("        }")
            .AppendLine("        catch")
            .AppendLine("        {")
            .AppendLine("            ((global::AsyncEventBridge.Unity.IAsyncEventBridgeInspectorSource)this).DisconnectInspectorEvents();")
            .AppendLine("            throw;")
            .AppendLine("        }")
            .AppendLine("    }")
            .AppendLine()
            .AppendLine("    void global::AsyncEventBridge.Unity.IAsyncEventBridgeInspectorSource.DisconnectInspectorEvents()")
            .AppendLine("    {")
            .AppendLine("        if (!__aebInspectorEventsConnected)")
            .AppendLine("        {")
            .AppendLine("            return;")
            .AppendLine("        }")
            .AppendLine()
            .AppendLine("        __aebInspectorEventsConnected = false;");

        foreach (var item in events)
        {
            source.Append("        this.")
                .Append(EscapeIdentifier(item.EventSymbol.Name))
                .Append(" -= ")
                .Append(GetHandlerName(item.EventSymbol.Name))
                .AppendLine(";");
        }

        source.AppendLine("    }")
            .AppendLine();

        foreach (var item in events)
        {
            AppendHandler(source, item);
        }

        source.AppendLine("}");

        if (!typeSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            source.AppendLine("}");
        }

        context.AddSource(
            GetHintName(typeSymbol) + ".InspectorEvents.g.cs",
            SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static void AppendHandler(StringBuilder source, EventInfo item)
    {
        source.Append("    private void ")
            .Append(GetHandlerName(item.EventSymbol.Name))
            .Append('(')
            .Append(item.Classification.SenderType)
            .Append(" sender, ")
            .Append(item.Classification.EventArgsType)
            .AppendLine(" eventArgs)")
            .AppendLine("    {")
            .Append("        AsyncEventBridgeEvents.")
            .Append(EscapeIdentifier(item.EventSymbol.Name))
            .Append(item.Classification.IsTyped ? ".Invoke(eventArgs);" : ".Invoke();")
            .AppendLine()
            .AppendLine("    }")
            .AppendLine();
    }

    private static EventClassification Classify(IEventSymbol eventSymbol)
    {
        if (!(eventSymbol.Type is INamedTypeSymbol delegateType) ||
            delegateType.TypeKind != TypeKind.Delegate)
        {
            return EventClassification.Unsupported;
        }

        if (delegateType.Name == "EventHandler" &&
            delegateType.ContainingNamespace.ToDisplayString() == "System")
        {
            if (delegateType.TypeArguments.Length == 0)
            {
                return new EventClassification(
                    isSupported: true,
                    isTyped: false,
                    senderType: "global::System.Object",
                    eventArgsType: "global::System.EventArgs");
            }

            if (delegateType.TypeArguments.Length == 1 &&
                IsEventArgsCompatible(delegateType.TypeArguments[0]))
            {
                return new EventClassification(
                    isSupported: true,
                    isTyped: true,
                    senderType: "global::System.Object",
                    eventArgsType: RenderType(delegateType.TypeArguments[0]));
            }

            return EventClassification.Unsupported;
        }

        var invokeMethod = delegateType.DelegateInvokeMethod;
        if (invokeMethod is null ||
            !invokeMethod.ReturnsVoid ||
            invokeMethod.Parameters.Length != 2 ||
            invokeMethod.Parameters[0].RefKind != RefKind.None ||
            invokeMethod.Parameters[1].RefKind != RefKind.None ||
            invokeMethod.Parameters[0].Type.IsRefLikeType ||
            !IsEventArgsCompatible(invokeMethod.Parameters[1].Type))
        {
            return EventClassification.Unsupported;
        }

        return new EventClassification(
            isSupported: true,
            isTyped: true,
            senderType: RenderType(invokeMethod.Parameters[0].Type),
            eventArgsType: RenderType(invokeMethod.Parameters[1].Type));
    }

    private static bool CanGenerateFor(INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.TypeKind != TypeKind.Class ||
            typeSymbol.IsAbstract ||
            typeSymbol.Arity != 0 ||
            typeSymbol.ContainingType is not null ||
            !IsDerivedFrom(typeSymbol, MonoBehaviourMetadataName))
        {
            return false;
        }

        return typeSymbol.DeclaringSyntaxReferences
            .Select(reference => reference.GetSyntax())
            .OfType<ClassDeclarationSyntax>()
            .Any(declaration => declaration.Modifiers.Any(modifier => modifier.IsKind(SyntaxKind.PartialKeyword)));
    }

    private static bool CanAccessEvent(IEventSymbol eventSymbol, INamedTypeSymbol targetType)
    {
        if (SymbolEqualityComparer.Default.Equals(eventSymbol.ContainingType, targetType))
        {
            return true;
        }

        return eventSymbol.DeclaredAccessibility == Accessibility.Public ||
               eventSymbol.DeclaredAccessibility == Accessibility.Protected ||
               eventSymbol.DeclaredAccessibility == Accessibility.ProtectedOrInternal ||
               eventSymbol.DeclaredAccessibility == Accessibility.Internal;
    }

    private static IEnumerable<IEventSymbol> GetEvents(INamedTypeSymbol typeSymbol)
    {
        var hiddenNames = new HashSet<string>(StringComparer.Ordinal);
        INamedTypeSymbol? current = typeSymbol;
        var isTarget = true;

        while (current is not null && IsDerivedFromOrEqual(current, MonoBehaviourMetadataName))
        {
            if (!isTarget && HasAttribute(current))
            {
                yield break;
            }

            foreach (var eventSymbol in current.GetMembers().OfType<IEventSymbol>())
            {
                if (hiddenNames.Add(eventSymbol.Name))
                {
                    yield return eventSymbol;
                }
            }

            foreach (var member in current.GetMembers())
            {
                hiddenNames.Add(member.Name);
            }

            isTarget = false;
            current = current.BaseType;
        }
    }

    private static bool HasAttribute(INamedTypeSymbol typeSymbol)
    {
        return typeSymbol.GetAttributes().Any(attribute =>
            attribute.AttributeClass?.ToDisplayString() == AttributeMetadataName);
    }

    private static bool IsDerivedFrom(INamedTypeSymbol typeSymbol, string metadataName)
    {
        INamedTypeSymbol? current = typeSymbol.BaseType;
        while (current is not null)
        {
            if (current.ToDisplayString() == metadataName)
            {
                return true;
            }

            current = current.BaseType;
        }

        return false;
    }

    private static bool IsDerivedFromOrEqual(INamedTypeSymbol typeSymbol, string metadataName)
    {
        INamedTypeSymbol? current = typeSymbol;
        while (current is not null)
        {
            if (current.ToDisplayString() == metadataName)
            {
                return true;
            }

            current = current.BaseType;
        }

        return false;
    }

    private static bool IsEventArgsCompatible(ITypeSymbol typeSymbol)
    {
        INamedTypeSymbol? current = typeSymbol as INamedTypeSymbol;
        while (current is not null)
        {
            if (current.Name == "EventArgs" &&
                current.ContainingNamespace.ToDisplayString() == "System")
            {
                return true;
            }

            current = current.BaseType;
        }

        return false;
    }

    private static string GetAccessibility(INamedTypeSymbol typeSymbol)
    {
        return typeSymbol.DeclaredAccessibility == Accessibility.Public
            ? "public"
            : "internal";
    }

    private static string RenderType(ITypeSymbol typeSymbol)
    {
        return typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    private static string GetHandlerName(string eventName)
    {
        var builder = new StringBuilder("__AebInspectorOn");
        AppendEncodedName(builder, eventName);
        return builder.ToString();
    }

    private static string GetHintName(INamedTypeSymbol typeSymbol)
    {
        var builder = new StringBuilder();
        if (!typeSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            AppendEncodedName(builder, typeSymbol.ContainingNamespace.ToDisplayString());
            builder.Append("_DOT_");
        }

        AppendEncodedName(builder, typeSymbol.Name);
        return builder.ToString();
    }

    private static void AppendEncodedName(StringBuilder builder, string value)
    {
        foreach (var character in value)
        {
            switch (character)
            {
                case '.':
                    builder.Append("_DOT_");
                    break;
                case '_':
                    builder.Append("__");
                    break;
                default:
                    builder.Append(character);
                    break;
            }
        }
    }

    private static string EscapeIdentifier(string identifier)
    {
        return SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None
            ? identifier
            : "@" + identifier;
    }

    private readonly struct EventClassification
    {
        internal EventClassification(bool isSupported, bool isTyped, string senderType, string eventArgsType)
        {
            IsSupported = isSupported;
            IsTyped = isTyped;
            SenderType = senderType;
            EventArgsType = eventArgsType;
        }

        internal bool IsSupported { get; }
        internal bool IsTyped { get; }
        internal string SenderType { get; }
        internal string EventArgsType { get; }

        internal static EventClassification Unsupported =>
            new EventClassification(false, false, string.Empty, string.Empty);
    }

    private sealed class EventInfo
    {
        internal EventInfo(IEventSymbol eventSymbol, EventClassification classification)
        {
            EventSymbol = eventSymbol;
            Classification = classification;
        }

        internal IEventSymbol EventSymbol { get; }
        internal EventClassification Classification { get; }
    }

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol namespaceSymbol)
    {
        foreach (var type in namespaceSymbol.GetTypeMembers())
        {
            yield return type;

            foreach (var nested in GetNestedTypes(type))
            {
                yield return nested;
            }
        }

        foreach (var childNamespace in namespaceSymbol.GetNamespaceMembers())
        {
            foreach (var type in GetAllTypes(childNamespace))
            {
                yield return type;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> GetNestedTypes(INamedTypeSymbol typeSymbol)
    {
        foreach (var nested in typeSymbol.GetTypeMembers())
        {
            yield return nested;

            foreach (var descendant in GetNestedTypes(nested))
            {
                yield return descendant;
            }
        }
    }
}
